version: "3"

services:
  frontend:
    image: nginx
    ports:
      - "12345:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
  
  backend:
    build: ./backend
    ports:
      - "12346:3000"
    volumes:
      - ./backend/src:/home/app/src      
